dataset: Novamag
dataset_path: data/novamag-magnetism.csv

models:
  - linear
  - ridge
  - lasso
  - elasticnet
  - rf
  - xgb
  - svr
  - mlp

enable_data_visualization: true
enable_hyperparameter_tuning: true
enable_ablation_study: true

# evaluation_mode: holdout # or cross_validation
evaluation_mode: cross_validation

cv_folds: 5
cv_shuffle: true
cv_random_state: 0
